name: lineament-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.30.1
  - pip=25.2
  - python=3.13.0
  - pygmt=0.16.0
  - geopandas=1.1.1
  - pip:
      - imageio==2.37.0
      - ipympl==0.9.8
      - matplotlib==3.10.7
      - netcdf4==1.7.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pillow==11.3.0
      - pyproj==3.7.2
      - pytz==2025.2
      - rasterio==1.4.3
      - rioxarray==0.19.0
      - scikit-image==0.25.2
      - scipy==1.16.2
      - sympy==1.14.0
      - torch==2.8.0+cu128
      - torchsummary==1.5.1
      - torchvision==0.23.0+cu128
      - xarray==2025.10.1
      - choclo==0.3.2
      - harmonica==0.7.0
      - pooch==1.8.2
      - verde==1.8.1
      - boule==0.5.0
      - ensaio==0.7.0
      - gdal==3.10.0
      - geos==3.13.0
      - geotiff==1.7.4
      - hdf4==4.2.15
      - hdf5==1.14.3
      - proj==9.5.1
      - alphashape==1.3.1
      - h5netcdf==1.6.3
      - h5py==3.14.0
      - planetary-computer==1.0.0
      - pystac==1.14.1
      - pystac-client==0.9.0
      - shapely==2.1.1